name: $(SourceBranchName)_$(Build.BuildId)

trigger:
  batch: true
  branches:
    include:
      - main
      - preprod
  paths:
    exclude:
      - README.md
      - .gitignore


#=====================================================================#
# ┌───────────────────────────────────────────────────────────────────┐
# │                             MODIFICABLE                           │
# ├───────────────────────────────────────────────────────────────────┤
# Variables obtenidas del estandar de nombramiento para repositorios de código fuente
variables:
  - name: namespace
    value: 'devopsdummy'

  - name: tecnologia
    value: 'react'
    
  - name: componente
    value: 'holavite'

  - name: identificador
    value: 'mfe'

  - name: tipo
    value: 'frontend'
# └───────────────────────────────────────────────────────────────────┘
#=====================================================================#
 
  - ${{ if eq( variables['Build.SourceBranchName'],'main') }}:
      group: vg-${{ variables['Build.Repository.Name'] }}-prod
    ${{ elseif eq( variables['Build.SourceBranchName'],'preprod') }}:
      group: vg-${{ variables['Build.Repository.Name'] }}-preprod
      
  - name: ambiente
    ${{ if eq( variables['Build.SourceBranchName'], 'main') }}:
      value: 'prod'
    ${{ elseif eq( variables['Build.SourceBranchName'], 'preprod') }}:
      value: 'preprod'

resources:
  repositories:
    - repository: templates
      type: git
      name: DevOps/devops-pipeline-cicd
      ref: 'refs/heads/feature/segmentacion_templates'

    - repository: Openshift
      type: git
      name: Openshift
      ref: $(Build.SourceBranchName)

stages:
  - template: master-azure-pipelines.yaml@templates
    parameters:
      param_namespace: ${{ variables.namespace }}
      param_tecnologia: ${{ variables.tecnologia }}
      param_componente: ${{ variables.componente }}
      param_identificador: ${{ variables.identificador }}
      param_tipo: ${{ variables.tipo }}
      param_ambiente: ${{ variables.ambiente }}
      
      # ${{ if eq( variables['Build.SourceBranchName'],'main' ) }}:
      #   param_ambiente: "prod"
      # ${{ if eq( variables['Build.SourceBranchName'],'preprod' ) }}:
      #   param_ambiente: "preprod"

