name: CI/CD pipeline
on:
  push:
    branches:
      - main
      - preprod

jobs:
  deploy:
    name: Deploy to ${{ github.ref_name }}
    uses: jnpalomino-portfolio/devops-pipeline-cicd/.github/workflows/master-pipeline.yaml@main