name: App Deployment
on:
  push:
    branches:
      - main
      - preprod

jobs:
  call-template:
    uses: jnpalomino-portfolio/devops-pipeline-cicd/.github/workflows/master-pipeline.yaml@main
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}