name: ${{ github.ref_name }}_${{ github.run_id }}
on:
  push:
    branches:
      - main
      - preprod

jobs:
  deploy:
    uses: jnpalomino-portfolio/devops-pipeline-cicd/.github/workflows/master-pipeline.yaml@main